import pymysql
import cgi
conn=pymysql.connect(host='localhost',user='root',password='',db='stock')
a=conn.cursor()
print("content-text:text/html\r\n\r\n")
print("<html>")

res=cgi.FieldStorage()
ISINcode=str(res.getvalue('ISINcode'))
sql="select * from company where ISINcode="+"'"+ISINcode+"'";
display=a.execute(sql)
data=a.fetchall()
for i in data:
	print("<html>")
	print("<head>")
	print("<title> My Stock Market</title>")
	print("</head>")
	print("<body>")
	print("<form action=CompanyUpDe1.py>")
	print("<center>")
	print("<table border=1>")
	print("<caption>Company Update/Delete Form</caption>")
	print("<tr><td>Category ID</td><td><input type=text name=cgid value="+str(i[0])+"></td></tr>")
	print("<tr><td>Company Name</td><td><input type=text name=cpname value="+str(i[1])+"></td></tr>")
	print("<tr><td>Company ISINcode</td><td><input type=text name=ISINcode value="+str(i[2])+" readonly=true></td></tr>")
	print("<tr><td>Category Icon</td><td><img src="+str(i[3])+" height=100 width=100><input type=file name=cpicon></td><tr>")
	print("<tr><td>Company Website</td><td><input type=text name=cpweb value="+str(i[4])+"></td></tr>")
	print("<tr><td>Category Description</td><td><textarea rows=5 cols=30 name=cpdes>"+str(i[5])+"</textarea></td></tr>")
	print("<tr><td>Company IPO Price</td><td><input type=text name=ipop value="+str(i[6])+"></td></tr>")
	print("<tr><td>Company IPO Date</td><td><input type=text name=ipod value="+str(i[7])+"></td></tr>")
	print("<tr><td><input type=submit name=btn value=Update></td><td><input type=submit name=btn value=Delete></td></tr>")
	print("</table>")
	print("</center>")
	print("</form>")
	print("</body>")
	print("</html>")