import pymysql
import cgi
conn=pymysql.connect(host='localhost',user='root',password='',db='stock')
a=conn.cursor()
print("content-text:text/html\r\n\r\n")
print("<html>")

res=cgi.FieldStorage()
userlogin=str(res.getvalue('userlogin'))
userpwd=str(res.getvalue('userpwd'))
sql="select * from userreg where userlogin='"+userlogin+"' and userpwd='"+userpwd+"'";
display=a.execute(sql)
if display!=0:
	print("<html>")
	print("<head>")
	print("<title>My Stock Market</title>")
	print("<script type='text/javascript'>")
	print("function preback(){window.history.forward();}")
	print("setTimeout('preback()',0);")
	print("window.onunload=function(){null};")
	print("</script>")
	print("</head>")
		
	print("<body>")
	print("<div style='float:right'>")
	print("<form align='right' name='form1' method='post' action='userlogin.py'>")
	print("<label class='logoutLblPos'>")
	print("<input type='submit' name='submit2' id='submit2' value='log out'>")
	print("</label>")
	print("</form>")
	print("</div>")
	print("<center>")
	print("<table border=0>")
	print("<caption><font size=7> User Home Page</font></caption>")
	print("<tr><td>Header</td><td>Header</td></tr>")
	print("<tr><td><a href=CategoryDisplay.py target=aa>Category Display</a><br>")
	print("<a href=CompanyDisplay.py target=aa>Company Display</a><br>")
	print("<a href=AdvSearch.py target=aa>Advance Search</a><br>")
	print("<a href=ChangePassword.py target=aa>Change Password</a><br>")
	print("</td><td><iframe src=AdvSearch.py name=aa height=1000 width=1000 frameborder=0></iframe></td></tr>")
	print("<tr><td>Footer</td><td>Footer</td></tr>")
	print("</table>")
	print("</center>")
	print("</form>")
	print("</body>")
	print("</html>")
else:
	print("ID / Password Not Matched...")
	print("<a href=UserLogin.py>Login Again</a>")
conn.commit()
